import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Components 
import Navigation from '../components/layout/Navigation';
import Masthead from '../components/layout/Masthead';
import Footer from '../components/layout/Footer';
import About from '../components/layout/About';
import Projects from '../components/layout/Projects';
import WorkProcess from '../components/layout/WorkProcess';
import Contact from '../components/layout/Contact';

export default function Home() {
  

  return (
    <div>
      <Head>
        <title>Yasmani Cascante Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation />
        <Masthead />
      </header>

      <main>
      <About />
      <Projects />
      <WorkProcess />
      <Contact />
      </main>

      <div className='layer'></div>
      <Footer />
    </div>
  )
}
