import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// Components 
import Navigation from '../components/layout/Navigation';
import Masthead from '../components/layout/Masthead';
import Footer from '../components/layout/Footer';
import About from '../components/layout/About';
import ProjectsList from '../components/layout/ProjectsList';
import WorkProcess from '../components/layout/WorkProcess';
import Contact from '../components/layout/Contact';

import { Client } from '@notionhq/client';
import Cursor from '../components/ui/Cursor';
import {useState} from 'react';
import { motion } from "framer-motion";


export default function Home({projects}) {

  const [cursorHide, setCursorHide] = useState(false);

  const hoverDispatch = (e) => {
    const mouseEvent = e.type;
    // mouseenter
    // mouseleave
    // console.log('Aqui!', mouseEvent);
    if(mouseEvent == 'mouseenter') {
      setCursorHide(true)
    // console.log('Aqui!', cursorHide);
    } else {
      setCursorHide(false)
    }
  }

  
// const variants = {
//   hide: {
//     display: 'none',
//     width: 200,
//     height: 200,
//     opacity: 0
//   },
//   show: {
//     display: 'block',
//     width: 30,
//     height: 30,
//     opacity: 1
//   }
// }

  return (
    <div>
      <Head>
        <title>Yasmani Cascante Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation />
        <Masthead />
      </header>

      <main>
      {/* <About /> */}
      <About hoverDispatch ={hoverDispatch}/> 
      <ProjectsList projects={projects} />
      <WorkProcess />
      <Contact />
      </main>

      <div className='layer'></div>
      <Footer />
      {/* <motion.div
       variants={variants}
       animate={cursorVariant}
       transition={{ delay: .3, duration: 1 }}
      > */}
        <Cursor />
      {/* </motion.div> */}
    </div>
  )
}

export async function getStaticProps() {
  const notion = new Client({ auth: process.env.NOTION_API_KEY });
  const databaseId = process.env.NOTION_DATABASE_ID;

  const response = await notion.databases.query({
    database_id: databaseId
  });
  
  return {
    props: {
      projects: response.results
    }
  }
}